baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 10

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "Infero"
    subtitle = "the Algorithmic and Logical Reasoning Club"
    keywords = "programming"
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Infero IITH"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
      [[languages.en.menu.main]]
	    identifier = "resources"
		  name = "Resources"
		  url = "/resources"
    [[languages.en.menu.main]]
	    identifier = "acpl"
		  name = "ACPL"
		  url = "/acpl"
